name: dispatch-repo-event

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - name: Install dependencies
      run: npm install

    - name: Dispatch event
      uses: actions/github-script@v6
      with: 
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: 'gh-actions-playground-downstream',
            event_type: 'custom_event_type',
            client_payload: {
              context,
              merge: false
            }
          });
